### ISSUE TITLE
add timestamp to filenames

### ISSUE THREAD

**Issue by schablonski** [IpswichMapper/SwiftAddress#14]
Now the standard-filename is "survey.zip". If it exists it will be "survey (1).zip and so one. The osm-file is housenumber.osm

It would be nice to add a timestamp to the filename like _survey_20210224_160858.zip_ and _housenumber_20210224_160858.osm_

So it would be easier to identify the files from multiple surveys.

**Comment by IpswichMapper** [comment]
> survey_20210224_160858.zip
I don't know about you, but I've never found these types of date-time stamps that readable. 

I'd much prefer something like this:

"Scotland Road survey 22 Jan 2021.zip"

"22 Jan 2021" seems much more readable to me. 
However something like that is not language independant ("Jan" stands for january in english) , so it cannot be done automatically. However, the app opens your document picker, which allows you to change the name of the zip file before you save it. 

That's why  the filename is a generic "survey.zip" You are meant to change the name to something much readable & choose a folder you like before you save it in your document picker. Manually entered names will always be more readable and much more easy to identify than automatically created names.

I could add the automatic datetime stamp if you still really want it for some reason, however that might discourage people from renaming the files, which will make them harder to identify.

**Comment by stephan75** [comment]
Timestamps beginning with year month day ... and hour minute seconds are better sortable by filename.

**Comment by IpswichMapper** [comment]
Can't you sort by Modified date anyway?

I can add the automatic timestamp if you really want it, but I still feel that manual naming is easier.

**Comment by IpswichMapper** [comment]
@schablonski @stephan75 

Do you really want this? I can add if you really want it, even though I would much prefer to manually rename the files.

**Comment by stephan75** [comment]
I strongly vote for this date format as YYYY-MM-DD as part of the filename.

**Comment by IpswichMapper** [comment]
Done
