### ISSUE TITLE
wish: notes export like osm-file

### ISSUE THREAD

**Issue by osmvermesser** [IpswichMapper/SwiftAddress#20]
i think it would be easier to intergrate notes in josm by osm-files.

regards Jan

**Comment by IpswichMapper** [comment]
They are already in .osc file? This is very easily openable in JOSM. Is there any alternative better file format that I don't know of?

**Comment by osmvermesser** [comment]
you create a osm-objekt with only a name-tag and so the information will show in josm without click the note-marker:

example

![notes2osm](https://user-images.githubusercontent.com/6803899/110163213-143b8480-7df0-11eb-96d7-9cd2b9d4c2f2.png)

you could export both file - there are not very large normally.

regards Jan

**Comment by IpswichMapper** [comment]
This is definately interesting, however this creates an OSM data file which you can upload. This should not be the case because these notes are NOT osm data. 

Therefore I use a ".osc" file which creates blue "note markers" on the map.

I know that the blue note markers have issues, but the JOSM dev team should probably fix that as well.

Also, you cannont show two OSM-object layers at once. Therefore, it wouldn't be that useful anyway. If these notes were created in the same layer as the housenumbers, then there is the risk of accidentally uploading them to openstreetmap.org, which is not good.
