### ISSUE TITLE
Option to modify increment for keypad increment/decrement buttons

### ISSUE THREAD

**Issue by osmvermesser** [IpswichMapper/SwiftAddress#24]
In the keypad you can Up down the number with +/-.

In german the inkrement normal ist 2 in each side.

So i would prefer a inkrement to define in option. Like the function in Josm.

Jan

**Comment by IpswichMapper** [comment]
![image](https://user-images.githubusercontent.com/72318451/110219520-9fcc1880-7eb7-11eb-83e3-2864860cd289.jpeg)
Here is the option to change the increment. You simply "swipe up" on the increment button.

You can also change increment in the "mini swipe up display" by pressing the gear in the top right.

**Comment by osmvermesser** [comment]
Nice - but in this moment it would bei nice to show a little temp Message about the new added number.

In the otherside i would prefer to connect the inkrement to the -/+ Buttons.

**Comment by IpswichMapper** [comment]
> Nice - but in this moment it would bei nice to show a little temp Message about the new added number.

what do you mean?

> In the otherside i would prefer to connect the inkrement to the -/+ Buttons.

the "increment" is for auto-incremeting. "Auto-incrementing" happens when you long press on the arrows below the map or swipe up on those arrows. 

As for the buttons, they will stick to only incrementing by 1. The reason for this is because if you want to increment more than once, you can simply press the auto-increment button twice. If, on the other hand, you want to incrment only once, and the increment option that you chose manually is bigger than one, then you have to change the increment option simply to increment by one. This will become more of a hassle.
