### ISSUE TITLE
need to reinstall swiftaddress when updating to 0.3.0

### ISSUE THREAD

**Issue by BrackoNe** [IpswichMapper/SwiftAddress#31]
I have installed the latest version, but as soon as you start the app - it crashes.

Samsung Note 10+, Android 11

**Comment by BrackoNe** [comment]
Solution: Completely uninstalled the app and reinstalled it. Now it works.

**Comment by IpswichMapper** [comment]
Probably something to do with the database change

**Comment by IpswichMapper** [comment]
Yep, it was a database error.

In this update, I completely changed the database so it attempts to delete the database and create a new one.

However, in my code I only told it to delete one table from the database, not the entire database. Therefore, when it tried to recreate the database, it failed because I hadn't deleted the entire database.

Fixed in this commit: d2b542c72579e4ba7e0eec41a6cd7512d9e0d81f
