### ISSUE TITLE
increment/decemrent by 2

### ISSUE THREAD

**Issue by BrackoNe** [IpswichMapper/SwiftAddress#32]
Please, make an option to save some taps by adding automatic increment or decrement by 2 once you tap to add a house number.

Math is simple here:
If you have 200 house numbers to add, it is ~100 odd and ~100 even house numbers:
- You have to tap 100 times for the left and 100 times for the right side to enter the screen for adding numbers
- then, you have to tap 100 x 2 on the +/- button for even and 100 x 2 on the +/- button for odd house numbers
- then, you have 100 x 2 to tap on an "OK" button (excluding building level swipes)
**Total: 800 taps**, instead of to tick increment/decrement option and:
- point to a house number, set the initial house number, and then just continue acquisition by tapping the "OK" button.
**Total taps after optimization: 200**

Please ask for more details if you need them.

**Comment by IpswichMapper** [comment]
This feature already exists :)

After you've entered the first house number on the left and right, try swiping up and long pressing on the arrows. (These are two superfast ways of entering housenumbers compared to the default method)

**Comment by BrackoNe** [comment]
But still extra taps/swipes. It would be nice to have an option to enable/disable by default.

**Comment by IpswichMapper** [comment]
What do you mean? Once you have added the first address, and each next address is only one tap each.

![signal-2021-03-28-230616](https://user-images.githubusercontent.com/72318451/112769687-3e144f80-901a-11eb-9c39-08d2ce6bfcc0.png)

**Comment by BrackoNe** [comment]
OK, I will test it out again. Maybe I have done something wrong.

**Comment by IpswichMapper** [comment]
Here is the math using the "swipe up" feature.

Adding the first address is 4 taps. Adding first address on right is also 4 taps, and the 1 tap to swipe up.

Adding all the next addresses is 1 tap each, so that is 198 taps.

Assuming you have to switch side every 4 addresses, that is an extra swipe every 4 addresses.

So that is 10 + 198 + 50, in total roughly 260 swipes. That is not far off your ideal number.

**Comment by BrackoNe** [comment]
Sounds good, just to see what I was doing wrong.

**Comment by IpswichMapper** [comment]
Please tell me when you have finished testing and understood when this all works. It is a bit confusing now because I have not written a guide explaining how it works, and I also have not got any tips in the app itself.

There are two methods of adding housenumbers quickly. On of them is long pressing on the arrow. This automatically adds a housenumber an "increment" higher/lower than your previous one **without the building levels**. (for example, if the increment is 3, and the previous housenumber was "23", long pressing will add "26").

Swiping up brings up a mini layout that lets you also quickly add housenumbers, but this time you can choose which building levels to use with the housenumber.

**Comment by BrackoNe** [comment]
It seems to work as expected just wasn't aware of this feature.
