### ISSUE TITLE
FairPhone Open OS : SwiftAddress not linked to system geolocation

### ISSUE THREAD

**Issue by Dubs120** [IpswichMapper/SwiftAddress#4]
I don't know what kind of geolocation service is used by SwiftAddress.

My FairPhone is under FairPhone OPEN OS, without any google service. The geolocation service is the GPS basic one, and it works perfectly with OSMand~ for example.

SwiftAddress don't detect anything... May be it should suitable to add a menu to customize/adjust some parameters?

**Comment by Dubs120** [comment]
@IpswichMapper : This morning, I noticed that SwiftAddress launches system Geolocation service.
I will test it in outdoor when battery will be full...

**Comment by Dubs120** [comment]
@IpswichMapper : I don't know why, but this time, geolocation was right, and little yellow figure appears!

I Had to write, it would be necessary to adjust final location since the used map seems to be based on "cadastre", and need to be relocated on true location.

**Comment by IpswichMapper** [comment]
I used the default geolocation code provided here:

https://github.com/osmdroid/osmdroid/wiki/How-to-use-the-osmdroid-library#how-to-add-the-my-location-overlay

I don't know what the problem is and what exactly this code does.

Is it that this code doesn't use the internet for location (Google/Mozilla location services) and only uses the inbuilt GPS sensor?

**Comment by Dubs120** [comment]
Hello @IpswichMapper !
From my understanding, the code ask the system geolocation... whatever is the used technology, Google/Mozilla location services or inbuilt GPS and compass. At the end, it is only coordinates and orientation.

My concern was about the initial "no link" between SwiftAddress and my system geolocation.But this morning, it worked!

My remark isn't about SwiftAddress geolocation but about the current OpenStreetMap accuracy in this area. I know it is based on official building definition, and need to be relocated wrt OrthoDB. And, since I placed house numbers wrt the map, when I will adjust the streets location, I would have also to adjust house numbers locations.

We can close this issue!
But, how to suggest an improvement?
It seems necessary to add a menu to customize the application : first zoom level, first location on the map, etc...
And, the possibility to display previous markers, saved on the phone, and to center the map on!

**Comment by IpswichMapper** [comment]
menu seems like a useful feature. I have added it to the list of missing features in the readme file.

> My concern was about the initial "no link" between SwiftAddress and my system geolocation.But this morning, it worked!

So what was the problem? Has it got anything to do with the osmdroid code?

> And, the possibility to display previous markers, saved on the phone

I won't add this, because "saving" the housenumbers suggests that you have done a survey and want to move those housenumbers to JOSM to upload. If you aren't finished with the survey: simply don't save the housenumbers - they are already saved in a database in the app. They are deleted from the database once you hit the save button, and moved to a file which you can open in JOSM.

Instead, I think it is a better idea to add a "confirmation window" that asks "are you sure?" when you try and save housenumbers.

> center the map on

I just added buttons to the to center the map, zoom in and zoom out, change the orientation to north.

You will be able to use them in the next release.

**Comment by IpswichMapper** [comment]
added a new release with new buttons

**Comment by Dubs120** [comment]
@IpswichMapper v0.1.4 tested today : good evolution! My system geolocation was very long to start in SwiftAddress compare to OSMAnd~, but at the end, it worked!
